### ISSUE TITLE
[Mobile] Home page

### ISSUE THREAD

**Issue by jeevonang** [ghuerte/ibinex-i#10]
![screenshot-ibinex local-2018 03 23-13-15-19 - copy](https://user-images.githubusercontent.com/37648409/37808921-1ea694e2-2ea1-11e8-848d-e14b920be7c8.png)

- section height = viewport height
- button alignment

<hr>

![screenshot-ibinex local-2018 03 23-13-15-19 - copy 2](https://user-images.githubusercontent.com/37648409/37809033-9232a66c-2ea1-11e8-9378-bd95bb61f6eb.png)

- section padding
- content font weight

<hr>

![screenshot-ibinex local-2018 03 23-13-15-19 - copy 3](https://user-images.githubusercontent.com/37648409/37809075-bb5f297a-2ea1-11e8-87f3-852c54a62d12.png)

- section padding
- font size & weight

<hr>

![screenshot-ibinex local-2018 03 23-13-15-19 - copy 4](https://user-images.githubusercontent.com/37648409/37809105-d0639b44-2ea1-11e8-97d4-48b1ba8950ce.png)

- missing content

<hr>

![screenshot-ibinex local-2018 03 23-13-45-56](https://user-images.githubusercontent.com/37648409/37809151-ffb9a582-2ea1-11e8-98bc-e6a8443898c0.png)

**Comment by stephenec** [comment]
Done na to
