### ISSUE TITLE
Unclickable Hamburger Menu

### ISSUE THREAD

**Issue by ghuerte** [ghuerte/ibinex-i#69]
The padding covers the hamburger menu thus it cannot be clicked..
![image](https://user-images.githubusercontent.com/37136794/38399161-32a2611c-397b-11e8-96b4-ef186173fdab.png)

**Comment by ricky-cabugawan** [comment]
bug fixed.

relevant commit: [https://github.com/ghuerte/ibinex-i/commit/32995a2a5d14b4d6388e8a0fabc52db1905e5d29](url)
