### ISSUE TITLE
[Desktop] Home page

### ISSUE THREAD

**Issue by jeevonang** [ghuerte/ibinex-i#9]
![screenshot-ibinex local-2018 03 22-20-00-56 - copy](https://user-images.githubusercontent.com/37648409/37806602-02b5e4ce-2e95-11e8-9cd8-58378fe86959.png)

Hero Section
- Hero section should have a same height as the viewport
- logo
- font size

<hr/>

![screenshot-ibinex local-2018 03 22-20-00-56 - copy 2](https://user-images.githubusercontent.com/37648409/37806876-8d626f88-2e96-11e8-952c-01bf785b9fdb.png)

- section header line height
- section padding

<hr/>

![screenshot-ibinex local-2018 03 22-20-00-56 - copy 3](https://user-images.githubusercontent.com/37648409/37806900-add997e6-2e96-11e8-8f7f-fb1cfc427600.png)

- section header line height
- sub header font color
- content font weight
- image
- section bottom padding

<hr/>

![screenshot-ibinex local-2018 03 22-20-00-56 - copy 4](https://user-images.githubusercontent.com/37648409/37807005-2388214c-2e97-11e8-8e3e-bd5278539d8e.png)

- excess section top padding
- header font color
- space between columns
- floating div background color and position

<hr/>

![screenshot-ibinex local-2018 03 22-20-00-56 - copy 6](https://user-images.githubusercontent.com/37648409/37807082-aa462030-2e97-11e8-94ed-b3cf382561b2.png)

- section top padding
- download button background and font color
- item name font color

<hr/>

![screenshot-ibinex local-2018 03 22-20-00-56 - copy 7](https://user-images.githubusercontent.com/37648409/37807149-11433886-2e98-11e8-9f44-3dcf1a693fc6.png)

- excess bottom padding
- footer column header font color

<hr/>

![screenshot-ibinex local-2018 03 22-20-00-56 - copy 8](https://user-images.githubusercontent.com/37648409/37807198-459ac806-2e98-11e8-9853-20756516cf69.png)

- logo 
- font color & weight
  * IBINEX OFFICES
  * SIGN UP TO OUR NEWSLETTER
  * FIND US ONLINE
- font

**Comment by stephenec** [comment]
Done na to
